name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_ios:
    name: Build iOS
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: xcodebuild build -scheme 'MMMSnapshotStorage' -destination generic/platform=iOS

  build_watchos:
    name: Build watchOS
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: xcodebuild build -scheme 'MMMSnapshotStorage' -destination generic/platform=watchOS
